### ISSUE TITLE
Docker toolchain images for Android

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#163]
## Tasks

So to clarify the scope of this issue, here is what needs to be done to come up with a minimal viable, but complete set of toolchain images and a workflow on top:

* [x] Toolchain image for Netty
* [x] WAMP demo client using Netty toolchain image
* [ ] Toolchain image for Android
* [ ] WAMP demo client using Android toolchain image

---

We should have 2 Dockerfiles in this repo:

* `/Dockerfile.android`
* `/Dockerfile.netty`

These Dockerfiles should contain the whole toolchain required, build the library and all examples/demos, and so on inside the container, and create final build artifacts (apks, jars, ..) in a volume mounted from the host.

That way, as a developer, I don't need any toolchain etc on my host, and have everything nicely fit together.

Besides _building_, the images should allow us to _run_ the demos/tests, eg.

1. run Android WebSocket echo client against AB testsuite
2. run Netty WebSocket echo client against AB testsuite
3. run Android WAMP demo client against a Crossbar.io in another container
4. run Netty WAMP demo client against a Crossbar.io in another container

Actually, what I'd like to do (after starting CB in another container):

```
make demo_wamp_netty
```

that would actually run (from the Makefile) sth similar to this:

```
docker run -v ${PWD}/.build:/build -it --rm --link crossbar crossbario/autobahn-java:netty java -jar /build/demo_wamp_netty.jar
```

**Comment by oberstet** [comment]
@om26er so this would be one area to continue work. I remember there were open questions rgd the Android SDK which we probably are not allowed to redistribute?

If so, best would be:

* we have a `Makefile` target to build the Android toolchain image, but don't publish it to Dockerhub
* developers would then need to clone this repo (which they likely want to do anyways), and then first build the Android toolchain image before actually using this locally built image then to build their apps

So nearly as comfy as with the Netty toolchain image, and I think the best we can do given licensing restrictions.

**Comment by om26er** [comment]
I actually think we may want to skip the Android toolchain images all together.

We cannot redistribute the Android SDK but the toolchain image building will expect the SDK to be installed on the host. We can safely assume that most (if not all) developers will only install the SDK on their systems for Android development so they already have Android Studio installed.

So any Android developer wanting to build the library or running example clients could simply use Android Studio

**Comment by oberstet** [comment]
> We cannot redistribute the Android SDK but the toolchain image building will expect the SDK to be installed on the host.

Ok, agreed.

However, even a toolchain image expecting the Android SDK (but nothing else) to reside on the host would be useful .. eg for CI purposes (where a headless CI server under own control, but with Android SDK installed).

Anyway, lets close it for now. We can still tackle it should we feel a real need ..
